---- MODULE trace_spec_no_rows ----
EXTENDS Sequences, TraceData

\* Keep this variable-free so Snowcat type annotations are not required
\* in the test spec itself; TraceData is generated by validate_trace.
TraceConstInit == TRUE
TraceInit == TRUE
TraceNext == TRUE

\* Inverted-invariant style: violation means a "valid" trace per crate API.
TraceFinished == Len(TraceActions) = 0
====
